In [1]:
import pandas as pd

In [2]:
df = pd.read_html("https://finance.yahoo.com/quote/FB/history?p=FBhttps://finance.yahoo.com/quote/FB/history?p=FB")[0]

In [3]:
df.head(3)

           Date    Open    High     Low  Close* Adj Close**    Volume
0  Jan 15, 2021  247.90  253.86  247.16  251.36      251.36  24786100
1  Jan 14, 2021  253.40  255.03  244.61  245.64      245.64  29739400
2  Jan 13, 2021  251.55  253.95  249.20  251.64      251.64  19528900

In [4]:
df = df.head(30).sort_values(by='Date')

In [5]:
df = df.astype({"Open":'float',
                "High":'float',
                "Low":'float',
                "Close*":'float',
                "Adj Close**":'float',
                "Volume":'float'})

In [6]:
df

            Date    Open    High     Low  Close*  Adj Close**      Volume
29  Dec 03, 2020  286.25  286.65  281.07  281.85       281.85  12921700.0
28  Dec 04, 2020  280.30  283.46  279.30  279.70       279.70  10880300.0
27  Dec 07, 2020  279.19  288.49  278.20  285.58       285.58  13007700.0
26  Dec 08, 2020  286.01  286.43  281.55  283.40       283.40  10747700.0
25  Dec 09, 2020  283.66  287.63  271.75  277.92       277.92  25189700.0
24  Dec 10, 2020  275.54  278.73  271.86  277.12       277.12  20065100.0
23  Dec 11, 2020  274.53  276.48  270.25  273.55       273.55  14391400.0
22  Dec 14, 2020  273.37  277.22  271.56  274.19       274.19  16376900.0
21  Dec 15, 2020  274.83  276.08  267.47  275.55       275.55  23979500.0
20  Dec 16, 2020  274.76  277.86  272.51  275.67       275.67  15885000.0
19  Dec 17, 2020  277.07  280.44  273.61  274.48       274.48  16377800.0
18  Dec 18, 2020  275.77  278.00  271.14  276.40       276.40  26693200.0
17  Dec 21, 2020  272.98  274.67  267.79  272.79       272.79  16553700.0
16  Dec 22, 2020  271.50  271.50  264.63  267.09       267.09  17312900.0
15  Dec 23, 2020  266.89  272.17  266.23  268.11       268.11  14329000.0
14  Dec 24, 2020  268.88  270.40  266.20  267.40       267.40   6702000.0
13  Dec 28, 2020  268.74  277.30  265.66  277.00       277.00  23299700.0
12  Dec 29, 2020  276.95  280.51  276.28  276.78       276.78  16383000.0
11  Dec 30, 2020  277.95  278.08  271.71  271.87       271.87  11803800.0
10  Dec 31, 2020  272.00  277.09  269.81  273.16       273.16  12892900.0
9   Jan 04, 2021  274.78  275.00  265.20  268.94       268.94  15106100.0
8   Jan 05, 2021  268.29  272.40  268.21  270.97       270.97   9871600.0
7   Jan 06, 2021  262.00  267.75  260.01  263.31       263.31  24354100.0
6   Jan 07, 2021  265.90  271.61  264.78  268.74       268.74  15789800.0
5   Jan 08, 2021  268.31  268.95  263.18  267.57       267.57  18512500.0
4   Jan 11, 2021  260.48  263.47  255.90  256.84       256.84  30412300.0
3   Jan 12, 2021  256.63  259.72  250.30  251.09       251.09  26449900.0
2   Jan 13, 2021  251.55  253.95  249.20  251.64       251.64  19528900.0
1   Jan 14, 2021  253.40  255.03  244.61  245.64       245.64  29739400.0
0   Jan 15, 2021  247.90  253.86  247.16  251.36       251.36  24786100.0

In [7]:
df.corr()

                 Open      High       Low    Close*  Adj Close**    Volume
Open         1.000000  0.969552  0.953856  0.930194     0.930194 -0.507354
High         0.969552  1.000000  0.963700  0.970387     0.970387 -0.487774
Low          0.953856  0.963700  1.000000  0.966699     0.966699 -0.627470
Close*       0.930194  0.970387  0.966699  1.000000     1.000000 -0.531713
Adj Close**  0.930194  0.970387  0.966699  1.000000     1.000000 -0.531713
Volume      -0.507354 -0.487774 -0.627470 -0.531713    -0.531713  1.000000

In [8]:
df['Gain'] = df['Close*']- df['Open']

In [9]:
df

,Date,Open,High,Low,Close*,Adj Close**,Volume,Gain
29,"Dec 03, 2020",286.25,286.65,281.07,281.85,281.85,12921700.0,-4.40
28,"Dec 04, 2020",280.30,283.46,279.30,279.70,279.70,10880300.0,-0.60
27,"Dec 07, 2020",279.19,288.49,278.20,285.58,285.58,13007700.0,6.39
26,"Dec 08, 2020",286.01,286.43,281.55,283.40,283.40,10747700.0,-2.61
25,"Dec 09, 2020",283.66,287.63,271.75,277.92,277.92,25189700.0,-5.74
24,"Dec 10, 2020",275.54,278.73,271.86,277.12,277.12,20065100.0,1.58
23,"Dec 11, 2020",274.53,276.48,270.25,273.55,273.55,14391400.0,-0.98
22,"Dec 14, 2020",273.37,277.22,271.56,274.19,274.19,16376900.0,0.82
21,"Dec 15, 2020",274.83,276.08,267.47,275.55,275.55,23979500.0,0.72
20,"Dec 16, 2020",274.76,277.86,272.51,275.67,275.67,15885000.0,0.91
19,"Dec 17, 2020",277.07,280.44,273.61,274.48,274.48,16377800.0,-2.59
18,"Dec 18, 2020",275.77,278.00,271.14,276.40,276.40,26693200.0,0.63
17,"Dec 21, 2020",272.98,274.67,267.79,272.79,272.79,16553700.0,-0.19
16,"Dec 22, 2020",271.50,271.50,264.63,267.09,267.09,17312900.0,-4.41
15,"Dec 23, 2020",266.89,272.17,266.23,268.11,268.11,14329000.0,1.22
14,"Dec 24, 2020",268.88,270.40,266.20,267.40,267.40,6702000.0,-1.48
13,"Dec 28, 2020",268.74,277.30,265.66,277.00,277.00,23299700.0,8.26
12,"Dec 29, 2020",276.95,280.51,276.28,276.78,276.78,16383000.0,-0.17
11,"Dec 30, 2020",277.95,278.08,271.71,271.87,271.87,11803800.0,-6.08
10,"Dec 31, 2020",272.00,277.09,269.81,273.16,273.16,12892900.0,1.16
9,"Jan 04, 2021",274.78,275.00,265.20,268.94,268.94,15106100.0,-5.84
8,"Jan 05, 2021",268.29,272.40,268.21,270.97,270.97,9871600.0,2.68
7,"Jan 06, 2021",262.00,267.75,260.01,263.31,263.31,24354100.0,1.31
6,"Jan 07, 2021",265.90,271.61,264.78,268.74,268.74,15789800.0,2.84
5,"Jan 08, 2021",268.31,268.95,263.18,267.57,267.57,18512500.0,-0.74
4,"Jan 11, 2021",260.48,263.47,255.90,256.84,256.84,30412300.0,-3.64
3,"Jan 12, 2021",256.63,259.72,250.30,251.09,251.09,26449900.0,-5.54
2,"Jan 13, 2021",251.55,253.95,249.20,251.64,251.64,19528900.0,0.09
1,"Jan 14, 2021",253.40,255.03,244.61,245.64,245.64,29739400.0,-7.76
0,"Jan 15, 2021",247.90,253.86,247.16,251.36,251.36,24786100.0,3.46